"""empty message

Revision ID: 1d7b69b07e23
Revises: c8ed8664b52b
Create Date: 2025-05-23 21:53:33.418211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7b69b07e23'
down_revision = 'c8ed8664b52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('original_file')

    # ### end Alembic commands ###
