"""empty message

Revision ID: cc5bb650c8ac
Revises: f51efad6fb59
Create Date: 2025-05-24 20:35:28.424013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc5bb650c8ac'
down_revision = 'f51efad6fb59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reader_settings')
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_book_progress', ['user_id', 'book_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reading_progress', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_book_progress', type_='unique')

    op.create_table('reader_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('font_size', sa.INTEGER(), nullable=True),
    sa.Column('theme', sa.VARCHAR(length=20), nullable=True),
    sa.Column('line_height', sa.FLOAT(), nullable=True),
    sa.Column('font_family', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
